apiVersion: v2
name: crowd
description: A chart for installing Crowd Data Center on Kubernetes
type: application
version: 1.1.0
appVersion: 4.4.0-jdk11
kubeVersion: ">=1.19.x-0"
keywords:
  - Crowd
  - Crowd Server
  - Crowd Data Center
  - Crowd DC
  - Atlassian
home: https://atlassian.github.io/data-center-helm-charts/
icon: https://atlassian.github.io/data-center-helm-charts/icons/crowd.svg
sources:
  - https://github.com/atlassian/data-center-helm-charts
  - https://bitbucket.org/atlassian-docker/docker-atlassian-crowd/
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/changes: |
    - kind: added
      description: Add support for custom schedulerName
      links:
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/301
    - kind: added
      description: Enable configuring ingress.class name
      links:
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/313
    - kind: changed
      description: Make security context more flexible
      links:
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/321
    - kind: added
      description: Roll Statefulset Pods if ConfigMap changes
      links:
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/315
    - kind: changed
      description: Crowd DC updated to 4.4.0 version
      links:
      - name: Github PR
        url: https://github.com/atlassian/data-center-helm-charts/pull/345